- name: Create directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  loop:
    - "/home/{{ ansible_user }}/{{ working_dir }}/{{ deploy_dir }}/config/file_sd"
  notify: Start/Recreate podman compose

- name: Copy templates files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "/home/{{ ansible_user }}/{{ working_dir }}/{{ deploy_dir }}/{{ item.dest }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  loop:
    - src: "compose.yml.j2"
      dest: "compose.yml"
    - src: "config/prometheus.yml.j2"
      dest: "config/prometheus.yml"
    - src: "config/file_sd/victoriametrics.yml.j2"
      dest: "config/file_sd/victoriametrics.yml"
  notify: Start/Recreate podman compose
