- name: Configure ip unprivileged port
  ansible.posix.sysctl:
    name: net.ipv4.ip_unprivileged_port_start
    value: "{{ [grafana_port] | min }}"
    reload: true

- name: Create directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  loop:
    - "/home/{{ ansible_user }}/{{ working_dir }}/{{ deploy_dir }}/config/provisioning/datasources"
  notify: Start/Recreate podman compose

- name: Copy templates files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "/home/{{ ansible_user }}/{{ working_dir }}/{{ deploy_dir }}/{{ item.dest }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  loop:
    - src: "compose.yml.j2"
      dest: "compose.yml"
  notify: Start/Recreate podman compose

- name: Generate datasource config per vm_remote_read_path
  ansible.builtin.template:
    src: "templates/config/provisioning/datasources/datasource-vm.yml.j2"
    dest: "/home/{{ ansible_user }}/{{ working_dir }}/{{ deploy_dir }}/config/provisioning/datasources/{{ read_path | regex_replace('^/', '') | regex_replace('/', '_') }}_datasources.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  loop: "{{ vm_remote_read_path }}"
  loop_control:
    loop_var: read_path
  notify: Start/Recreate podman compose
