- name: Configure ip unprivileged port
  ansible.posix.sysctl:
    name: net.ipv4.ip_unprivileged_port_start
    value: "{{ [grafana_port] | min }}"
    reload: true

- name: Create top directory
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/{{ working_dir }}/{{ deploy_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"

- name: Create directory
  ansible.builtin.file:
    path:
      "/home/{{ ansible_user }}/{{ working_dir }}/{{ deploy_dir }}/{{ item.path
      }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  with_filetree: "{{ role_path }}/templates"
  when: item.state == "directory"
  notify: Start/Recreate podman compose

- name: Generate datasource config per vm_remote_read_path
  ansible.builtin.template:
    src: "templates/config/provisioning/datasources/datasource-vm.yml.j2"
    dest: "/home/{{ ansible_user }}/{{ working_dir }}/{{ deploy_dir }}/config/provisioning/datasources/{{ read_path | regex_replace('^/', '') | regex_replace('/', '_') }}_datasources.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  loop: "{{ vm_remote_read_path }}"
  loop_control:
    loop_var: read_path
  notify: Start/Recreate podman compose
