- name: Create top directory
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/{{ working_dir }}/{{ deploy_dir }}/config"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"

- name: Create directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  loop:
    - "/home/{{ ansible_user }}/{{ working_dir }}/{{ deploy_dir }}/config"
  notify: Start/Recreate podman compose

- name: Copy files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "/home/{{ ansible_user }}/{{ working_dir }}/{{ deploy_dir }}/{{ item.path }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  with_filetree: "{{ role_path }}/files"
  when: item.state == "file"
  notify: Start/Recreate podman compose

- name: Copy templates files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "/home/{{ ansible_user }}/{{ working_dir }}/{{ deploy_dir }}/{{ item.dest }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  loop:
    - src: "compose.yml.j2"
      dest: "compose.yml"
  notify: Start/Recreate podman compose
