- name: Install container tools and create directory
  become: true
  hosts: all
  roles:
    - container

- name: Setup grafana
  become: true
  hosts: grafana
  roles:
    - grafana

- name: Setup vmauth
  become: true
  hosts: vmauth-read:vmauth-write
  roles:
    - vmauth

- name: Setup vmselect
  become: true
  hosts: vmselect
  roles:
    - vmselect

- name: Setup vminsert
  become: true
  hosts: vminsert
  roles:
    - vminsert

- name: Setup vmagent
  become: true
  hosts: vmagent
  roles:
    - vmagent

- name: Setup vmstorage
  become: true
  hosts: vmstorage
  roles:
    - vmstorage
