- name: Install packages
  ansible.builtin.dnf:
    name:
      - keepalived
    state: present

- name: Enable and start services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - keepalived

- name: Deploy keepalived configuration
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart keepalived

- name: Deploy check script
  ansible.builtin.template:
    src: check_vmauth.sh.j2
    dest: /usr/local/bin/check_vmauth.sh
    owner: root
    group: root
    mode: "0755"
  notify: Restart keepalived

- name: Enable and start keepalived services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - keepalived
